### ISSUE TITLE
Repo owner has abandoned this project

### ISSUE THREAD

**Issue by malero** [airtonix/angular-named-routes#25]
Is it time to make a fork of this project and allow the community to contribute to it? It's pretty easy to get npm, bower and similar package managers to change ownership on repos that are no longer maintained.

**Comment by airtonix** [comment]
Abandoned? no.

You're welcome to create tests that pass and submit pull requests.

**Comment by malero** [comment]
Great, thank you!

**Comment by airtonix** [comment]
I'm not even really sure how to respond to your attitude. I find it troubling that you feel such threats are a valid way to communicate.
